//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_First___Existing_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costumer()
        {
            this.Receit = new HashSet<Receit>();
        }
    
        public int CostumerNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CostumerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receit> Receit { get; set; }
    }
}
