//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_First___Existing_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receit
    {
        public int OrderId { get; set; }
        public Nullable<int> CostumerNo { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
    
        public virtual Costumer Costumer { get; set; }
    }
}
